name: Docker Setup QEMU

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: 'centos:6.10'

    steps:
    - uses: docker/setup-qemu-action@v1.2.0
    - name: Build the Docker image
      run:
